[package]
name = "rust"
version = "0.1.0"
authors = ["pstiegele <paul.stiegele@stud.tu-darmstadt.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.pnet]
version = "0.26.0"